### PR TITLE
Add CI built on GitHub Actions

### PR DESCRIPTION
**Pull request by geky**
Note: This depends on https://github.com/gwsystems/aWsm/pull/19, but it can be disentangled if needed. See https://github.com/gwsystems/aWsm/compare/51dc1d1...geky:testing-squished to see what's changed.

This PR adds support for CI built on GitHub Actions. I will tinker with it to make sure its working, but it may just automatically run. It should take any commits/PRs against this repo, build them against both wasmception and wasi-sdk, and push the resulting benchmarks.csv as a "artifact" to the workflow. I will aadd a comment once its working.

There's a small TODO list:
1. Host a precompiled wasmception binary somewhere. Currently I have the wasmception binary as a release on my repo [here](https://github.com/geky/aWsm/releases/tag/wasmception-0.1). You should just be able to download the `wasmception-0.1.tar.gz` and reupload to the repo you want to host from. Should this be Others/wasmception or gwsystems repo?

   Once hosting in a correct place I can update this PR to point there instead of my own repo.

2. Make sure GitHub actions is enabled on gwsystems/awsm. Just need to see what's needed here. This PR may just work without GitHub-side config, or it may not.

Anyways I just wanted to get this PR up for feedback, it should hopefully help build confidence on PRs to here.

### CODE REVIEW

**Comment by geky** [comment]
Should resolve https://github.com/gwsystems/aWsm/issues/17

**Comment by geky** [comment]
Oh hey, it's got a checkmark.
- CI log (wasi-sdk): https://github.com/gwsystems/aWsm/runs/1002187439?check_suite_focus=true
- CI log (wasmception): https://github.com/gwsystems/aWsm/runs/1002187422?check_suite_focus=true
- Benchmarks uploaded here: https://github.com/gwsystems/aWsm/actions/runs/214920499

**Comment by Others** [comment]
Consider this approved by me, as soon as everything under it is merged

**Comment by Others** [comment]
Ready to be merged after #19

**Comment by bushidocodes** [comment]
@geky - I cut a release from the head of the sfbase branch of wasmception of gwsystems, so a tarball is here: https://github.com/gwsystems/wasmception/releases/tag/v0.2.0. Can you please use that and rebase with master? Assuming things rebase cleanly, I suspect that this one should be ready to merge. If you're swamped, I can grab the diff you posted earlier and create a fresh PR. Let me know either way!

**Comment by bushidocodes** [comment]
FYI: I cherry picked the diff you linked above into #27 so I can try to bang this out.

**Pull request closed without merging**
